# Generated by Django 4.1.4 on 2022-12-29 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_alter_user_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
