# Generated by Django 4.1.4 on 2022-12-31 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_artist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
