# Generated by Django 4.1.4 on 2023-01-06 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0009_rename_series_serie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Serie',
        ),
    ]
